name: agenda_contatos
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  sqflite: ^1.2.0
  url_launcher: ^5.4.1
  image_picker: ^0.6.3+1
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - imgs/profile_default.jpg  